databases:
  - name: garden
    databaseName: garden
    user: garden

services:
  - type: web
    name: garden
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn garden.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: garden
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4